import type { ColorTheme, ColorHex, ColorRGB } from '@/types/types';

export const DarkColorTheme: ColorTheme = {
    isDark: true,
    background: '#000000',
    primary: '#ffffff',
    secondary: '#999999',
    foreground: '#111111',
    borders: '#333333',
    accent: '#00aaff',
};
export const LightColorTheme: ColorTheme = {
    isDark: false,
    background: '#ffffff',
    primary: '#000000',
    secondary: '#666666',
    foreground: '#eeeeee',
    borders: '#cccccc',
    accent: '#0055ff',
};
export const Accents = {
    DarkRed: '#800000' as ColorHex,
    Red: '#FF0000' as ColorHex,
    LightRed: '#FF8080' as ColorHex,
    DarkOrange: '#804000' as ColorHex,
    Orange: '#FF8000' as ColorHex,
    LightOrange: '#FFBF80' as ColorHex,
    DarkYellow: '#808000' as ColorHex,
    Yellow: '#FFFF00' as ColorHex,
    LightYellow: '#FFFF80' as ColorHex,
    DarkGreen: '#008000' as ColorHex,
    Green: '#00FF00' as ColorHex,
    LightGreen: '#80FF80' as ColorHex,
    DarkAqua: '#008080' as ColorHex,
    Aqua: '#00FFFF' as ColorHex,
    LightAqua: '#80FFFF' as ColorHex,
    DarkBlue: '#000080' as ColorHex,
    Blue: '#0000FF' as ColorHex,
    LightBlue: '#8080FF' as ColorHex,
    DarkPurple: '#400080' as ColorHex,
    Purple: '#8000FF' as ColorHex,
    LightPurple: '#BF80FF' as ColorHex,
    DarkMagenta: '#800080' as ColorHex,
    Magenta: '#FF00FF' as ColorHex,
    LightMagenta: '#FF80FF' as ColorHex,
    DarkPink: '#800040' as ColorHex,
    Pink: '#FF0080' as ColorHex,
    LightPink: '#FF80BF' as ColorHex,
};